# Generated by Django 2.1.5 on 2019-02-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturecomment',
            name='user',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
