# Generated by Django 2.1.5 on 2019-02-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_summernote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summernote',
            name='attachment_ptr',
        ),
        migrations.DeleteModel(
            name='SummerNote',
        ),
    ]
